### PR TITLE
update gnome runtime to v40

### PR DESCRIPTION
**Pull request by zyxmdvs**
This is my first pull request, please tell me if I did something wrong

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
You can drop the libhandy module, it's on the GNOME Sdk already.

**Comment by zyxmdvs** [comment]
Oops, I just see what I did wrong. I'll reverse it

**Comment by zyxmdvs** [comment]
I think I did it right this time. I don't know whether I should close this pull request, so I'll leave it open just in case.

**Comment by zyxmdvs** [comment]
I just downloaded and tested the build. It all seems to work well on my machine. But you will want to do some further testing yourself.

**Comment by xou816** [comment]
Hi! Missed this PR, thanks for the contribution. Let me test this, otherwise we're good to merge!

**Comment by xou816** [comment]
I was a bit quick to merge, no big deal but don't hesitate to squash/amend your commits to make the git history more readable! :)

**Pull request merged**
